prx:
  auth:
    converter:
      resource-id: ${AUTH_CLIENT_ID}
      principal-claim-name: ${AUTH_RESOURCE_PRINCIPAL}
  security:
    keystore:
      location: ${SSL_JKS_CNFS_KEYSTORE_LOCATION}
      type: ${SSL_JKS_CNFS_KEYSTORE_TYPE}
      password: ${SSL_JKS_CNFS_KEYSTORE_PASSWORD}
    truststore:
      location: ${SSL_JKS_CNFS_TRUSTSTORE_LOCATION}
      type: ${SSL_JKS_CNFS_TRUSTSTORE_TYPE}
      password: ${SSL_JKS_CNFS_TRUSTSTORE_PASSWORD}
    management-authenticator:
      enabled: true
      keystore:
        location: ${SSL_JKS_CNFS_KEYSTORE_LOCATION}
        type: ${SSL_JKS_CNFS_KEYSTORE_TYPE}
        password: ${SSL_JKS_CNFS_KEYSTORE_PASSWORD}
      truststore:
        location: ${SSL_JKS_CNFS_KEYSTORE_LOCATION}
        type: ${SSL_JKS_CNFS_TRUSTSTORE_TYPE}
        password: ${SSL_JKS_CNFS_TRUSTSTORE_PASSWORD}

app:
  name: jobs-backend-api
  version: 1.0.0
  api:
    endpoint: /jobs-backend/api/v1
#<><><><><><><><><><><><><><> HTTPS <><><><><><><><><><><><><><>
server:
  port: ${JOBS_OFFER_PORT}
  http2:
    enabled: true
#<><><><><><><><><><><><><><> SPRING <><><><><><><><><><><><><><>
spring:
  application:
    name: ${app.name}
    description: Jobs Backend API
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  server:
    port: ${server.port}
    ssl:
      enabled: true
      bundle: jobs-offer-security
  #<><><><><><><><><><><><><><> DATABASES <><><><><><><><><><><><><><>
  datasource:
    username: ${JOB_OFFERS_DB_USERNAME}
    password: ${JOB_OFFERS_DB_PASSWORD}
    url: jdbc:postgresql://${JOB_OFFERS_DB_URI}:${JOB_OFFERS_DB_PORT}/${JOB_OFFERS_DB_NAME}
    driver-class-name: org.postgresql.Driver
    #<><><><><><><><><><><><><><> CONNECTION POOL <><><><><><><><><><><><><><>
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      poolName: SpringBootJPAHikariCP-JobsBackend
      idleTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 5
  #<><><><><><><><><><><><><><> PERSISTENCE <><><><><><><><><><><><><><>
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      jdbc:
        lob.non_contextual_creation: true
    log-level: error
  test:
    context:
      failure:
        threshold: 10000000
  #<><><><><><><><><><><><><><> SSL <><><><><><><><><><><><><><>
  ssl:
    bundle:
      jks:
        jobs-offer-security:
          key:
            alias: ${SSL_KEY_ALIAS}
          keystore:
            location: classpath:${SSL_KEYSTORE_LOCATION}
            password: ${SSL_KEYSTORE_PASSWORD}
            type: ${SSL_KEYSTORE_TYPE}
          trust-store:
            location: classpath:${SSL_JKS_CNFS_TRUSTSTORE_LOCATION}
            password: ${SSL_JKS_CNFS_TRUSTSTORE_PASSWORD}
            type: ${SSL_JKS_CNFS_TRUSTSTORE_TYPE}
#<><><><><><><><><><><><><><> CLOUD <><><><><><><><><><><><><><>
cloud:
  discovery:
    enabled: true
  inetutils:
    ignoredInterfaces:
      - docker
      - eth.*
      - lo
    preferredNetworks:
      - 172.18.0
  output:
    ansi:
      enabled: DETECT
  #<><><><><><><><><><><><><><> JMX <><><><><><><><><><><><><><>
  jmx:
    default-domain: ${JMX_DEFAULT_DOMAIN}
  data:
    rest:
      base-path: /api
#<><><><><><><><><><><><><><> SERVICE DISCOVERY <><><><><><><><><><><><><><>
eureka:
  client:
    application:
      name: ${app.name}
    enabled: on
    tls:
      trust-store-type: ${SSL_JKS_SRMN_TRUSTSTORE_TYPE}
      trust-store-password: ${SSL_JKS_SRMN_TRUSTSTORE_PASSWORD}
      trust-store: classpath:${SSL_JKS_SRMN_TRUSTSTORE_LOCATION}
      key-store-type: ${SSL_JKS_SRMN_KEYSTORE_TYPE}
      key-store-password: ${SSL_JKS_SRMN_KEYSTORE_PASSWORD}
      key-store: classpath:${SSL_JKS_SRMN_KEYSTORE_LOCATION}
      key-password: ${SSL_JKS_SRMN_KEYSTORE_PASSWORD}
    # Port for the Eureka server
    eurekaServerPort: ${SRMN_PORT}
    # DNS name for the Eureka server
    eurekaServerDNSName: ${SRMN_URI}
    # Enables fetching the registry from Eureka
    fetch-registry: true
    # Enables registration with Eureka
    register-with-eureka: ${SRMN_REGISTER_ENABLED}
    serviceUrl:
      # Default zone for the Eureka server
      defaultZone: ${SRMN_URI}:${SRMN_PORT}/eureka/
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    # Disables non-secure port
    nonSecurePortEnabled: false
    # Enables secure port
    securePortEnabled: true
    # Hostname for the Eureka instance
    hostName: ${SRMN_HOSTNAME}
#<><><><><><><><><><><><><><> OPEN API DOC <><><><><><><><><><><><><><>
springdoc:
  version: ${app.version}
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: All
      paths-to-match: ${app.api.endpoint}/**/**
    - group: Companies
      paths-to-match: ${app.api.endpoint}/companies/**
    - group: Job-offers
      paths-to-match: ${app.api.endpoint}/job-offers/**
    - group: Modes
      paths-to-match: ${app.api.endpoint}/modes/**
    - group: Reports
      paths-to-match: ${app.api.endpoint}/reports/**
    - group: Position
      paths-to-match: ${app.api.endpoint}/positions/**
    - group: Sources
      paths-to-match: ${app.api.endpoint}/sources/**
    - group: Source-types
      paths-to-match: ${app.api.endpoint}/source-types/**
    - group: Status
      paths-to-match: ${app.api.endpoint}/status/**
    - group: Terms
      paths-to-match: ${app.api.endpoint}/terms/**
