app:
  name: jobs-backend-api
  version: 0.0.1-01-2024
  api:
    endpoint: /api/v1
#<><><><><><><><><><><><><><> HTTPS <><><><><><><><><><><><><><>
server:
  port: 8183
  ssl:
    enabled: true
    bundle: config-server
#<><><><><><><><><><><><><><> SPRING <><><><><><><><><><><><><><>

spring:
  cloud:
    vault:
      enabled: false
  application:
    name: ${app.name}
    description: Jobs Backend API
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  server:
    port: ${server.port}
    ssl:
      enabled: true
      bundle: config-server
  test:
    context:
      failure:
        threshold: 10000000
#<><><><><><><><><><><><><><> DATABASES <><><><><><><><><><><><><><>
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    driver-class-name: org.postgresql.Driver
#<><><><><><><><><><><><><><> CONNECTION POOL <><><><><><><><><><><><><><>
    hikari:
      connectionTimeout: 30000
      maxLifetime: 1800000
      poolName: SpringBootJPAHikariCP-JobsBackend
      idleTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 5
  #<><><><><><><><><><><><><><> SSL <><><><><><><><><><><><><><>
  ssl:
    bundle:
      jks:
        config-server:
          key:
            alias: ${SSL_JKS_CONFIG_SERVER_KEY_ALIAS}
          keystore:
            location: ${SSL_JKS_CONFIG_SERVER_KEYSTORE_LOCATION}
            password: ${SSL_JKS_CONFIG_SERVER_KEYSTORE_PASSWORD}
            type: ${SSL_JKS_CONFIG_SERVER_KEYSTORE_TYPE}
#<><><><><><><><><><><><><><> CLOUD <><><><><><><><><><><><><><>
cloud:
  discovery:
    enabled: true
  inetutils:
    ignoredInterfaces:
      - docker
      - eth.*
      - lo
    preferredNetworks:
      - 172.18.0
  output:
    ansi:
      enabled: DETECT
  #<><><><><><><><><><><><><><> JMX <><><><><><><><><><><><><><>
  jmx:
    default-domain: ${JMX_DEFAULT_DOMAIN}
    data:
      rest:
        base-path: /api
  # The Spring Cloud Config specific configurations
  #<><><><><><><><><><><><><><> VAULT <><><><><><><><><><><><><><>
  vault:
    token: ${VAULT_TOKEN}
    uri: ${VAULT_SERVER_URL}
    kv:
      backend: PRX
      default-context: ${app.name}
    application-name: ${app.name}
  bootstrap:
    # Enables the Spring Cloud Bootstrap application context
    enabled: ${SPRING_BOOT_CLOUD_BOOTSTRAP_ENABLED}
#<><><><><><><><><><><><><><> SERVICE DISCOVERY <><><><><><><><><><><><><><>
eureka:
  instance:
    home-page-url: ${EUREKA_HOME_PAGE_URL_PATH}
    preferIpAddress: true
    prefer-ip-address: true
    hostName: ${EUREKA_HOSTNAME}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    health-check-url: ${EUREKA_HEALTH_CHECK_URL_PATH}
    status-page-url-path: ${EUREKA_STATUS_PAGE_URL_PATH}
  client:
    healthcheck: true
    port: ${EUREKA_PORT}
    url: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
    enabled: false
#<><><><><><><><><><><><><><> OPEN API DOC <><><><><><><><><><><><><><>
springdoc:
  version: ${app.version}
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: all
      paths-to-match: ${app.api.endpoint}/**/**
    - group: companies
      paths-to-match: ${app.api.endpoint}/companies/**
    - group: job-offers
      paths-to-match: ${app.api.endpoint}/job-offers/**
    - group: modes
      paths-to-match: ${app.api.endpoint}/modes/**
    - group: reports
      paths-to-match: ${app.api.endpoint}/reports/**
    - group: position
      paths-to-match: ${app.api.endpoint}/positions/**
    - group: sources
      paths-to-match: ${app.api.endpoint}/sources/**
    - group: source-types
      paths-to-match: ${app.api.endpoint}/source-types/**
    - group: status
      paths-to-match: ${app.api.endpoint}/status/**
    - group: terms
      paths-to-match: ${app.api.endpoint}/terms/**