# Configuration for PRX authentication and security settings
prx:
  bootstrap:
    server:
      url: ${BOOTSTRAP_SERVER_URI}
  consumer:
    mercury:
      topic: ${MERCURY_EMAIL_TOPIC}
  auth:
    converter:
      resource-id: ${AUTH_CLIENT_ID}  # Resource ID for the authentication client
      principal-claim-name: ${AUTH_RESOURCE_PRINCIPAL}  # Principal claim name for the resource
  security:
    keystore:
      location: ${SSL_JKS_CNFS_KEYSTORE_LOCATION}  # Location of the keystore
      type: ${SSL_JKS_CNFS_KEYSTORE_TYPE}  # Type of the keystore
      password: ${SSL_JKS_CNFS_KEYSTORE_PASSWORD}  # Password for the keystore
    truststore:
      location: ${SSL_JKS_CNFS_TRUSTSTORE_LOCATION}  # Location of the truststore
      type: ${SSL_JKS_CNFS_TRUSTSTORE_TYPE}  # Type of the truststore
      password: ${SSL_JKS_CNFS_TRUSTSTORE_PASSWORD}  # Password for the truststore
    management-authenticator:
      enabled: true  # Enable management authenticator
      keystore:
        location: ${SSL_JKS_CNFS_KEYSTORE_LOCATION}  # Location of the keystore for management
        type: ${SSL_JKS_CNFS_KEYSTORE_TYPE}  # Type of the keystore for management
        password: ${SSL_JKS_CNFS_KEYSTORE_PASSWORD}  # Password for the keystore for management
      truststore:
        location: ${SSL_JKS_CNFS_KEYSTORE_LOCATION}  # Location of the truststore for management
        type: ${SSL_JKS_CNFS_KEYSTORE_TYPE}  # Type of the truststore for management
        password: ${SSL_JKS_CNFS_KEYSTORE_PASSWORD}  # Password for the truststore for management

# Application-specific settings
app:
  name: mercury
  version: 0.0.1
  api:
    endpoint: /api/v1

# Server configuration
server:
  port: ${APP_PORT}  # Port for the server
  http2:
    enabled: true  # Enable HTTP/2

# Spring framework configuration
spring:
  application:
    name: ${app.name}  # Name of the Spring application
    description: Mercury API  # Description of the Spring application
  main:
    allow-bean-definition-overriding: true  # Allow bean definition overriding
    banner-mode: console  # Set banner mode to console
  server:
    port: ${APP_PORT}  # Port for the Spring server
    ssl:
      enabled: true  # Enable SSL
      bundle: mercury-security  # SSL bundle name
  # Database configuration
  datasource:
    username: ${MERCURY_DB_USERNAME}  # Username for the database
    password: ${MERCURY_DB_PASSWORD}  # Password for the database
    url: jdbc:postgresql://${MERCURY_DB_URI}:${MERCURY_DB_PORT}/${MERCURY_DB_NAME}  # JDBC URL for the database
    driver-class-name: org.postgresql.Driver  # Driver class name for PostgresSQL

    # Connection pool settings
    hikari:
      connectionTimeout: 30000  # Connection timeout for HikariCP
      maxLifetime: 1800000  # Maximum lifetime for HikariCP connections
      poolName: SpringBootJPAHikariCP-DirectoryBackend  # Pool name for HikariCP
      idleTimeout: 30000  # Idle timeout for HikariCP
      minimumIdle: 1  # Minimum idle connections for HikariCP
      maximumPoolSize: 5  # Maximum pool size for HikariCP

  # JPA (Java Persistence API) settings
  jpa:
    hibernate.ddl-auto: none  # Hibernate DDL auto setting
    show-sql: false  # Show SQL statements
    database: POSTGRESQL  # Database type
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgresSQL
    properties:
      jdbc:
        lob.non_contextual_creation: true  # Non-contextual LOB creation
    log-level: error  # Log level for JPA
#<><><><><><><><><><><><><><> MONGO DB <><><><><><><><><><><><><><>
  data:
    mongodb:
      uuidRepresentation: STANDARD
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}?retryWrites=true&w=majority
  #<><><><><><><><><><><><><><> EMAIL <><><><><><><><><><><><><><>
  mail:
    host: ${MAIL_HOST} #TODO Must be change with Dynamic value
    port: ${MAIL_PORT} #TODO Must be change with Dynamic value
    username: ${MAIL_USERNAME} #TODO Must be change with Dynamic value
    password: ${MAIL_PASSWORD} #TODO Must be change with Dynamic value
    default-encoding: ${MAIL_PROPERTIES_DEFAULT_ENCODING}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        timeout: ${MAIL_PROPERTIES_TIMEOUT}
        smtp:
          auth: ${MAIL_PROPERTIES_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_STARTTLS_ENABLED}
            required: ${MAIL_PROPERTIES_STARTTLS_REQUIRED}
          ssl:
            enable: ${MAIL_PROPERTIES_SSL_ENABLED}
    test-connection: ${MAIL_PROPERTIES_TEST_CONNECTION}
  freemarker:
    template-loader-path: ${TEMPLATE_PATH}
    suffix: ${TEMPLATE_SUFFIX}

  # SSL configuration
  ssl:
    bundle:
      jks:
        mercury-security:
          key:
            alias: ${SSL_KEY_ALIAS}  # Alias for the SSL key
          keystore:
            location: classpath:${SSL_KEYSTORE_LOCATION}  # Location of the keystore
            password: ${SSL_KEYSTORE_PASSWORD}  # Password for the keystore
            type: ${SSL_KEYSTORE_TYPE}  # Type of the keystore
          trust-store:
            location: classpath:${SSL_JKS_CNFS_TRUSTSTORE_LOCATION}  # Location of the truststore
            password: ${SSL_JKS_CNFS_TRUSTSTORE_PASSWORD}  # Password for the truststore
            type: ${SSL_JKS_CNFS_TRUSTSTORE_TYPE}  # Type of the truststore

# Cloud configuration
cloud:
  discovery:
    enabled: true  # Enable cloud discovery
  inetutils:
    ignoredInterfaces:
      - docker  # Ignore docker interfaces
      - eth.*  # Ignore ethernet interfaces
      - lo  # Ignore loopback interfaces
    preferredNetworks:
      - 172.18.0  # Preferred network range
  output:
    ansi:
      enabled: DETECT  # Enable ANSI output detection

  # JMX (Java Management Extensions) settings
  jmx:
    default-domain: ${JMX_DEFAULT_DOMAIN}  # Default domain for JMX

  data:
    rest:
      base-path: /api/v1  # Base path for REST data

# Eureka service discovery configuration
eureka:
  client:
    jersey:
      enabled: false
    restclient:
      enabled: false
    application:
      name: ${app.name}  # Name of the Eureka client application
    enabled: on  # Enable Eureka client
    tls:
      trust-store-type: ${SSL_JKS_SRMN_TRUSTSTORE_TYPE}  # Trust store type for TLS
      trust-store-password: ${SSL_JKS_SRMN_TRUSTSTORE_PASSWORD}  # Trust store password for TLS
      trust-store: classpath:${SSL_JKS_SRMN_TRUSTSTORE_LOCATION}  # Trust store location for TLS
      key-store-type: ${SSL_JKS_SRMN_KEYSTORE_TYPE}  # Key store type for TLS
      key-store-password: ${SSL_JKS_SRMN_KEYSTORE_PASSWORD}  # Key store password for TLS
      key-store: classpath:${SSL_JKS_SRMN_KEYSTORE_LOCATION}  # Key store location for TLS
      key-password: ${SSL_JKS_SRMN_KEYSTORE_PASSWORD}  # Key password for TLS
    eurekaServerPort: ${SRMN_PORT}  # Port for the Eureka server
    eurekaServerDNSName: ${SRMN_URI}  # DNS name for the Eureka server
    fetch-registry: true  # Enable fetching the registry from Eureka
    register-with-eureka: ${SRMN_REGISTER_ENABLED}  # Enable registration with Eureka
    serviceUrl:
      defaultZone: ${SRMN_DEFAULT_ZONE}  # Default zone for the Eureka server
  instance:
    preferIpAddress: false  # Prefer IP address for Eureka instance
    leaseRenewalIntervalInSeconds: 10  # Lease renewal interval for Eureka instance
    leaseExpirationDurationInSeconds: 30  # Lease expiration duration for Eureka instance
    nonSecurePortEnabled: false  # Disable non-secure port
    securePortEnabled: true  # Enable secure port
    hostName: ${SRMN_HOSTNAME}  # Hostname for the Eureka instance

# Open API documentation configuration
springdoc:
  version: ${app.version}  # Version of the Open API documentation
  api-docs:
    version: openapi_3_1  # Version of the Open API specification
  swagger-ui:
    display-request-duration: true  # Display request duration in Swagger UI
    groups-order: DESC  # Order groups in descending order
    operationsSorter: method  # Sort operations by method
    disable-swagger-default-url: true  # Disable default Swagger URL
    use-root-path: true  # Use root path for Swagger UI
  show-actuator: true  # Show actuator endpoints in Swagger UI
  group-configs:
    - group: All  # Group for all endpoints
      paths-to-match: ${app.api.endpoint}/**/**
    - group: Users  # Group for company-related endpoints
      paths-to-match: ${app.api.endpoint}/mail

camel:
  springboot:
    main-run-controller: ${CAMEL_MAIN_RUN_CONTROLLER}
  # Token ID del Bot utilizado
  #<><><><><><><><><><><><><><> TELEGRAM CLIENT <><><><><><><><><><><><><><>
  component:
    telegram:
      authorization-token: ${TELEGRAM_TOKEN_ID}
telegram:
  url: https://api.telegram.org/bot${TELEGRAM_TOKEN_ID}/sendMessage
  parser-mode: ${TELEGRAM_PARSE_MODE}

cache:
  infinispan:
    config: classpath:infinispan.xml
  emails-messages:
    id: ${CACHE_EMAIL_MESSAGE_ID}
    expiration: 300
    time-unit: SECONDS
    maximum-size: 1000
    initial-capacity: 1000
    eviction: LRU
    eviction-strategy: LIRS
    eviction-max-entry-size: 1000
    eviction-max-entries: 1000
    eviction-thread-pool-size: 10
    eviction-thread-pool-priority: 5
    eviction-wake-up-interval: 1000
    eviction-wake-up-interval-time-unit: MILLISECONDS
    eviction-max-thread-runs: 1000
    eviction-max-size: 1000
    eviction-min-size: 1000
    eviction-min-time-to-live: 1000
    eviction-max-time-to-live: 1000
    eviction-lifo: true
    eviction-async: true
    eviction-async-pool-size: 10
    eviction-async-pool-priority: 5
    eviction-async-wake-up-interval: 1000
    eviction-async-wake-up-interval-time-unit: MILLISECONDS
    eviction-async-max-thread-runs: 1000
    eviction-async-min-size: 1000
    eviction-async-min-time-to-live: 1000
    eviction-async-max-time-to-live: 1000
    eviction-async-lifo: true
    eviction-async-store: true
    eviction-async-store-thread-pool-size: 10
    eviction-async-store-thread-pool-priority: 5
    eviction-async-store-wake-up-interval: 1000
    eviction-async-store-wake-up-interval-time-unit: MILLISECONDS
    eviction-async-store-max-thread-runs: 1000
    eviction-async-store-min-size: 1000
    eviction-async-store-min-time-to-live: 1000
    eviction-async-store-max-time-to-live: 1000
    eviction-async-store-lifo: true
    eviction-async-store-timeout: 1000
    eviction-async-store-timeout-time-unit: MILLISECONDS
    eviction-async-store-queue-size: 1000
    eviction-async-store-flush-lock-timeout: 1000

codekey:
  message:
    INF_001: '[${spring.profiles.active}] Acceso autorizado'
    INF_002: '[${spring.profiles.active}] Acción completada'
    INF_003: '[${spring.profiles.active}] Usuario ya se encuentra con una sesion activa'
    INF_004: '[${spring.profiles.active}] Sesion de usuario terminada'
    INF_005: '[${spring.profiles.active}] Comando sin programar'
    WAR_001: '[${spring.profiles.active}] Acceso NO autorizado'
    WAR_002: '[${spring.profiles.active}] Usuario no existe'
    WAR_003: '[${spring.profiles.active}] Comando vacio'
    WAR_004: '[${spring.profiles.active}] Comando NO valido'
    WAR_005: '[${spring.profiles.active}] Usuario NO esta activo'
