---
app:
  name: '@pom.artifactId@'
  version: '@pom.artifactId@'
#<><><><><><><><><><><><><><> SERVER <><><><><><><><><><><><><><><><><><><><><>
server:
  port: 8002
  #<><><><><><><><><><><><><><> HTTPS <><><><><><><><><><><><><><><><><><><><><>
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: prx_backbone_rest.jks
    key-store-password: prx-backbone-rest
    key-store-type: JKS
    key-alias: prx-backbone-rest
#<><><><><><><><><><><><><><> SPRING <><><><><><><><><><><><><><><><><><><><>
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
    application:
      name: ${app.name}
      description: Cliente del proveedor Bitfinex
    cloud:
      inetutils:
        ignoredInterfaces:
          - docker
          - eth.*
          - lo
        preferredNetworks:
          - 172.18.0
  output:
    ansi:
      enabled: DETECT
  data:
    rest:
      base-path: /api
  rabbitmq:
    port: 5762
    host: localhost
    username: lmata
    password: 13515030
    client:
      routing-key: data
      exchange: instruments
#<><><><><><><><><><><><><><> SWAGGER <><><><><><><><><><><><><><><><><><><><>
swagger:
  base-package: 'com.prx.rt.provider.bitfinex.controller'
  api-info:
    title: 'PRX RT Bitfinex'
    description: 'Cliente Rest para obtencion de datos publicados por Bitfinex'
    contact:
      name: 'Luis Antonio Mata'
      url: 'www.prx.test'
      email: 'luis.antonio.mata@gmail.com'
#<><><><><><><><><><><><><><> FEIGN <><><><><><><><><><><><><><><><><><><><>
feign:
  client:
    default-to-properties: false
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    exchange:
      find: '/prx-market-provider-config/manager/exchange/find/{token}/{idExchange}'
    put-info-ticker: '/prx-bridge/hub/putInfoTicker'
#<><><><><><><><><><><><><><> LOGGING <><><><><><><><><><><><><><><><><><><>
logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
      hibernate: INFO
      com:
        prx: INFO
#<><><><><><><><><><><><><><> SCHEDULER <><><><><><><><><><><><><><><><><><>
schedule:
  bitfinex-scheduler:
    find-market-value: '*/1 * * * * *'
  properties-scheduler:
    load-instrument-by-exchange: '0 0 */1 * * *'
  backup-scheduler:
    find-market-value: '*/20 * * * * *'
    rolling-file-date: '0 0 0 * * *'
#<><><><><><><><><><><><><><> BITFINEX CLIENT <><><><><><><><><><><><><><>
client:
  exchange:
    id: 2
    name: Bitfinex
    #<><><><><><><><><><><><><><> REST <><><><><><><><><><><><><><><><><><><><>
    rest:
      tickers:
        url: 'https://api.bitfinex.com/v2/tickers?symbols=ALL'
        # Expresados en minutos
        max-time-delay: 120
        exchange.find.enabled: true
        exchange-instrument.find.enabled: false
        print: false
    #<><><><><><><><><><><><><><> WEBSOCKET <><><><><><><><><><><><><><><><><>
    websocket:
      tickets:
        url: 'wss://api-pub.bitfinex.com/ws/2'
#<><><><><><><><><><><><><><> HTTPS PARA BASE DE DATOS <><><><><><><><><><><><><><>
postgres:
    service:
        url: database-1.csoaiazs7rxp.sa-east-1.rds.amazonaws.com
        name: postgres
        database: pawfairy
        username: usr_genweb
        password: UsU075qjjgCtdWxS3rxgjwCoCmWjdQ1FrhBYapZs
#<><><><><><><><><><><><><><> EUREKA <><><><><><><><><><><><><><><><><><><>
eureka:
  client:
    url: localhost
    port: 8763
    register-with-eureka: true
    enable: true
    healtcheck: true
    serviceUrl:
      defaultZone: https://${eureka.client.url}:${eureka.client.port}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 30
    hostName: localhost
    preferIpAddress: true
    status-page-url-path: https://${eureka.instance.hostName}:${server.port}/actuator/info
    health-check-url: https://${eureka.instance.hostName}:${server.port}/actuator/health
    home-page-url: https://${eureka.instance.hostName}:${server.port}/
    port: ${server.port}
#<><><><><><><><><><><><><><> BACKUP <><><><><><><><><><><><><><><><><><><>
bkp:
  file-name: ${app.name}.dat
  directory: '/opt/bkp/${app-name}/'
debug: false
